name: sooraac
description: safe and reliable taxi service
full_description: 'We are the fastest and safest transportation option in somalia. A pool of +1000 vehicles are on standby, on every corner, to service your needs, 24 hrs a day, 7 days a week, including Holidays.<br>'
android: http://sooraac.com
iOS: http://sooraac.com
web: http://sooraac.com
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
producthunt: http://sooraac.com
companies:
  - url: http://sooraac.com
    image: androidpolice.png
  - url: http://sooraac.com
    image: producthunt.png
